name: thermal-analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - scipy>=1.7.0
  - scikit-image>=0.18.0
  - pillow>=8.0.0
  - tk>=8.6
  - pytest>=6.0.0
  - black>=21.0.0
  - flake8>=3.9.0
  - mypy>=0.910
  - plotly>=5.5.0
  - pip>=21.0.0
  - pip:
    - cairosvg>=2.5.2
    - pywebview>=3.6.0
    - python-dateutil>=2.8.2
    - pytz>=2021.1
    - six>=1.16.0
    - cairocffi>=1.3.0
    - tinycss2>=1.1.1
    - cssselect2>=0.4.1
    - defusedxml>=0.7.1
    # Platform-specific dependencies
    - pyobjc-core>=9.0.1; sys_platform == 'darwin'  # macOS only
    - pyobjc-framework-Cocoa>=9.0.1; sys_platform == 'darwin'  # macOS only
    - pyobjc-framework-Quartz>=9.0.1; sys_platform == 'darwin'  # macOS only
    - pywin32>=306; sys_platform == 'win32'  # Windows only
